### ISSUE TITLE
Multiple window "scroll" events on the window may cause bugs

### ISSUE THREAD

**Issue by nicolasblanco** [PJUllrich/pragprog-book-tables#1]
Hello!

Thanks for your book, I've bought it and I'm currently reading it 👍🏻 .

I would like to make a small comment about the infinite scrolling part. About 1 year ago, I implemented it a bit the same way you did and had an "hard-to-debug" issue.

The issue was more or less this: basically by using `window.addEventListener` directly inside the `mounted` function of the hook, there were cases where multiple identical events were attached to the `window`. So basically every time the user was using live navigation, it would add a new `scroll` event to the window. Something which is not really wanted.

The issue I had is that at some point, the JavaScript was pushing the event to a dead LiveView and causing the page to reload because multiple scroll events were bound on the window and one of them was triggered on a dead LiveView.

I fixed the issue by removing the scroll event using `removeEventListener` when the LiveView gets destroyed, something like that:

```
mounted() {
  // ...
  window.addEventListener("scroll", this.boundInfiniteScroll);
  // ...
},
destroyed() {
  // ...
  window.removeEventListener("scroll", this.boundInfiniteScroll);
  // ...
}
```

_Note that the removeEventListener function needs a reference to the exact callback function that was added_

**Comment by PJUllrich** [comment]
Thank you very much for this suggestion, @nicolasblanco 🙏 

I changed the code, but had to reference the evenListener like this:

```
window.addEventListener("scroll", () => this.boundInfiniteScroll());
```

Otherwise, the eventListener wasn't bind to `this` 🤷 .
I hope this is acceptable JavaScript as well :D
