### ISSUE TITLE
Ecto.ParameterizedType.init/2

### ISSUE THREAD

**Issue by LostKobrakai** [PJUllrich/pragprog-book-tables#2]
https://github.com/PJUllrich/pragprog-book-tables/blob/d2e3825067e1a332dd33172719f5916fed888aa0/lib/meow/ecto_helper.ex#L3

There‘s a way in ecto itself to do that: 
https://hexdocs.pm/ecto/Ecto.ParameterizedType.html#init/2

**Comment by PJUllrich** [comment]
Hmm, thank you for the suggestion 🙏 

Could you help me to understand this a bit better, please?

Do you suggest to create a custom parameterized type like this for example?

```elixir
defmodule Meow.EnumParam do
  use Ecto.ParameterizedType
end

defmodule MeowWeb.Forms.SortingForm do
  alias Meow.EnumParam

  @fields {
     sort_by: EnumParam.init([:id, :name]),
     sort_dir: EnumParam.init([:asc, :desc])
 }
end
```

_(I haven't tested this code)_

**Comment by PJUllrich** [comment]
Oh nevermind. I realised only later that `Ecto.ParameterizedType` offers an `init/2` function.

So, I guess, you meant this solution, right?

```elixir
defmodule Meow.EctoHelper do
  def enum(values) do
    Ecto.ParameterizedType.init(Ecto.Enum, values: values)
  end
end

```

**Comment by LostKobrakai** [comment]
Yeah and with that I'm wondering if it actually makes sense to keep this helper module or just call `Ecto.ParameterizedType.init(Ecto.Enum, values: values)` where the helper module is used atm.

**Comment by PJUllrich** [comment]
Hmm, yeah I see your point. Maybe, maybe not. I think it helps the readability of the `@fields`-definitions in the forms a bit, that's why I'll keep it. But thanks for pointing this out 🙏
