### ISSUE TITLE
Unexpected behaviour when filter and pagination live components interact

### ISSUE THREAD

**Issue by prsn-uk** [PJUllrich/pragprog-book-tables#3]
@PJUllrich thanks for this well written and informative book.

**Issue**

When a filter is applied to a paginated list the current page is not being reset - this sometimes causes the list to appear empty.

**Reproduce**

- Go to page 2 of the meerkat list page.
- Add a filter for meerkat name.
- If there are not enough records to reach the second page the entire list will appear empty.

**Solution?**

[Reset page to 1 in `MeowWeb.MeerkatLive` when new filter is detected](https://github.com/PJUllrich/pragprog-book-tables/blob/0c9e28198ae3f14e6d7d79460b4fff62813ba893/lib/meow_web/live/meerkat_live.ex#L23)

**Comment by PJUllrich** [comment]
Hey @prsn-uk 👋 thanks for the bug report! I'll update the book accordingly :)

**Comment by PJUllrich** [comment]
Thanks again @prsn-uk  🙏 I updated the code here and will update the book later today. See the changes here: https://github.com/PJUllrich/pragprog-book-tables/commit/0352606ad82ecc1c7d9f34ce5fc93de07f7c2dc9
